name: CI / Price comparator

on: [push, pull_request]

jobs:
  quality:
    name: Quality
    defaults:
      run:
        working-directory: /tmp
    runs-on: ubuntu-22.04
    if: ${{ always() }}
    timeout-minutes: 1
    concurrency:
      group: ${{ github.workflow }}-qa-${{ github.ref }}
      cancel-in-progress: true
    needs:
      - qa-typescript
    steps:
      - run: echo "::group::Quality checks"

  qa-typescript:
    name: Quality
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    concurrency:
      group: ${{ github.workflow }}-qa-ts-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: 📥 Monorepo install
        uses: ./.github/actions/yarn-nm-install
      - name: Check coding standards
        run: yarn run format:check
      - name: Make static analysis (rome)
        run: yarn run lint:check
      - name: Make static analysis (typescript)
        run: yarn run typescript:check
