name: CI / Price comparator

on:
  push:
    branches:
      - gh-readonly-queue/master/**
  pull_request:
    paths:
      - '.github/workflows/ci-comparator.yaml'
      - './**'

jobs:
  quality:
    name: Quality
    defaults:
      run:
        working-directory: /tmp
    runs-on: ubuntu-22.04
    if: ${{ always() }}
    timeout-minutes: 1
    concurrency:
      group: ${{ github.workflow }}-qa-${{ github.ref }}
      cancel-in-progress: true
    needs:
      - qa-typescript
      - qa-check-translations
    steps:
      - run: echo "::group::Quality checks"

  qa-typescript:
    name: Quality
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    concurrency:
      group: ${{ github.workflow }}-qa-ts-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: priceComparatorCR/setup-repo-node-app@v1.3
        with:
          node-version: 16
          working-directory: landing
      - name: Check coding standards
        run: yarn run format:check
      - name: Make static analysis (rome)
        run: yarn run lint:check
      - name: Make static analysis (typescript)
        run: yarn run typescript:check
